export const FETCH_QUIZ_SUCCESS = 'quiz/FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAILURE = 'quiz/FETCH_QUIZ_FAILURE';
export const UPDATE_CURRENT_QUESTION = 'quiz/UPDATE_CURRENT_QUESTION';
export const UPDATE_CORRECT_ANSWERS = 'quiz/UPDATE_CORRECT_ANSWERS';
export const UPDATE_TIME_LEFT = 'quiz/UPDATE_TIME_LEFT';
export const RESET_STATE = 'quiz/RESET_STATE';
export const DEFAULT_QUIZ_DURATION = 180;
